import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { initLocalWorkspace } from "./local-workspace.js";
import {
  buildSmtProblem,
  parseSmtConstraint,
  solveSmtProblem
} from "./smt-problem.js";
import type { SmtBackendCommandRunner } from "./smt-backend.js";
import { validateWorkspaceArtifacts } from "./workspace-validation.js";

const tempRoots: string[] = [];

afterEach(async () => {
  await Promise.all(tempRoots.map((root) => rm(root, { recursive: true, force: true })));
  tempRoots.length = 0;
});

describe("SMT problem builder", () => {
  it("parses explicit integer constraints", () => {
    expect(parseSmtConstraint("x + y >= 3")).toEqual({
      source: "x + y >= 3",
      left: "x + y",
      operator: ">=",
      right: "3",
      variables: ["x", "y"]
    });
  });

  it("builds reviewable SMT-LIB from structured integer constraints", () => {
    const result = buildSmtProblem({
      queryName: "small_positive_integer",
      variables: ["x"],
      constraints: ["x > 0", "x < 3"],
      includeModel: true
    });

    expect(result.problemId).toMatch(/^smt_problem_[a-f0-9]{16}$/);
    expect(result.logic).toBe("QF_NIA");
    expect(result.sourceText).toContain("; Generated by Truth Harness");
    expect(result.sourceText).toContain("; Query: small_positive_integer");
    expect(result.sourceText).toContain("(declare-const x Int)");
    expect(result.sourceText).toContain("(assert (> x 0))");
    expect(result.sourceText).toContain("(assert (< x 3))");
    expect(result.sourceText).toContain("(check-sat)");
    expect(result.sourceText).toContain("(get-model)");
    expect(result.limitations.join(" ")).toContain("integer variables");
  });

  it("rejects undeclared variables and unsupported operations", () => {
    expect(() =>
      buildSmtProblem({
        variables: ["x"],
        constraints: ["y > 0"]
      })
    ).toThrow("undeclared variable");

    expect(() =>
      buildSmtProblem({
        variables: ["x"],
        constraints: ["x / 2 > 1"]
      })
    ).toThrow("Division is not supported");
  });

  it("writes generated SMT-LIB sources, checks them, and validates workspace records", async () => {
    const root = await tempRoot();
    await initLocalWorkspace(root, { displayName: "SMT Solve Lab" });
    const runner: SmtBackendCommandRunner = (_command, args) => {
      if (args[0] === "-version") {
        return {
          status: 0,
          stdout: "Z3 version 4.13.0\n",
          stderr: ""
        };
      }

      return {
        status: 0,
        stdout: "sat\n(\n  (define-fun x () Int\n    1)\n)\n",
        stderr: ""
      };
    };

    const result = await solveSmtProblem({
      rootPath: root,
      queryName: "small_positive_integer",
      variables: ["x"],
      constraints: ["x > 0", "x < 3"],
      includeModel: true,
      now: new Date("2026-06-11T00:00:00.000Z"),
      runner
    });
    const source = await readFile(result.sourcePath, "utf8");
    const validation = await validateWorkspaceArtifacts({ rootPath: root });

    expect(result.sourceRef).toContain(".truth-harness/smt/sources/");
    expect(result.sourceRef).toContain(result.problem.problemId);
    expect(source).toBe(result.problem.sourceText);
    expect(result.check.record.trust).toBe("smt-checked");
    expect(result.check.record.model?.bindings).toEqual([
      {
        name: "x",
        sort: "Int",
        value: "1",
        raw: "(define-fun x () Int\n    1)"
      }
    ]);
    expect(result.check.record.source.path).toBe(result.sourceRef);
    expect(result.check.record.source.sha256).toMatch(/^[a-f0-9]{64}$/);
    expect(validation.passed).toBe(true);
    expect(validation.summary.byKind.smt).toBe(1);
  });
});

async function tempRoot(): Promise<string> {
  const root = await mkdtemp(join(tmpdir(), "truth-harness-smt-problem-"));
  tempRoots.push(root);
  return root;
}
